
version: "3.9"

services:
  execute-1:
    image: tscel/geth:v1.13-base-v5
    container_name: execute-1
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "10000:8551"
      - "11000:8545"
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/execute1:/root/gethdata
    networks:
      - meta

  beacon-1:
    image: tscel/beacon-v5.0.1-t1-reorg:0805
    container_name: beacon-1
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.3/tcp/13000/p2p/16Uiu2HAmViS3SUn4cBmMGkRx6CBzgSFHu7JJY6oztwvbhzPKrQSQ  --peer /ip4/172.99.1.4/tcp/13000/p2p/16Uiu2HAkuVr12eYtMNuxcRcTYj9PYHxVTz8TYkDjGgg8ZtFWi2rP  --peer /ip4/172.99.1.5/tcp/13000/p2p/16Uiu2HAm42EM98s9Feq2VoWP6R78FtHs6T9sWY3HaGFn7assWc87  --peer /ip4/172.99.1.6/tcp/13000/p2p/16Uiu2HAmNhdZermeUdkQuZeathnkEiWHH8KFJcSsXPeTR3JA6Zue 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=f4138210a3f9805e47da011384d9109d968f76aa85d65348c02ab78aa7f2ce92

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13000:4000"
      - "14000:3500"
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/beacon-1:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.2

  beacon-2:
    image: tscel/beacon-v5.0.1-t1-reorg:0805
    container_name: beacon-2
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.2/tcp/13000/p2p/16Uiu2HAmDashuTodN3KUjWFM3yvcUE5h1qUHYGnEGJ98vFaFVB9W  --peer /ip4/172.99.1.4/tcp/13000/p2p/16Uiu2HAkuVr12eYtMNuxcRcTYj9PYHxVTz8TYkDjGgg8ZtFWi2rP  --peer /ip4/172.99.1.5/tcp/13000/p2p/16Uiu2HAm42EM98s9Feq2VoWP6R78FtHs6T9sWY3HaGFn7assWc87  --peer /ip4/172.99.1.6/tcp/13000/p2p/16Uiu2HAmNhdZermeUdkQuZeathnkEiWHH8KFJcSsXPeTR3JA6Zue 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=c4676d3a5b9026bb045d366a9c77922373050a7a4cc08d78d2423de08010a712

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13001:4000"
      - "14001:3500"
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/beacon-2:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.3

  beacon-3:
    image: tscel/beacon-v5.0.1-t1-reorg:0805
    container_name: beacon-3
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.2/tcp/13000/p2p/16Uiu2HAmDashuTodN3KUjWFM3yvcUE5h1qUHYGnEGJ98vFaFVB9W  --peer /ip4/172.99.1.3/tcp/13000/p2p/16Uiu2HAmViS3SUn4cBmMGkRx6CBzgSFHu7JJY6oztwvbhzPKrQSQ  --peer /ip4/172.99.1.5/tcp/13000/p2p/16Uiu2HAm42EM98s9Feq2VoWP6R78FtHs6T9sWY3HaGFn7assWc87  --peer /ip4/172.99.1.6/tcp/13000/p2p/16Uiu2HAmNhdZermeUdkQuZeathnkEiWHH8KFJcSsXPeTR3JA6Zue 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=34996cf9c006df01068469b3b075f88aabad343be623859e3695ac54a0f233d5

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13002:4000"
      - "14002:3500"
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/beacon-3:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.4

  beacon-4:
    image: tscel/beacon-v5.0.1-t1-reorg:0805
    container_name: beacon-4
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.2/tcp/13000/p2p/16Uiu2HAmDashuTodN3KUjWFM3yvcUE5h1qUHYGnEGJ98vFaFVB9W  --peer /ip4/172.99.1.3/tcp/13000/p2p/16Uiu2HAmViS3SUn4cBmMGkRx6CBzgSFHu7JJY6oztwvbhzPKrQSQ  --peer /ip4/172.99.1.4/tcp/13000/p2p/16Uiu2HAkuVr12eYtMNuxcRcTYj9PYHxVTz8TYkDjGgg8ZtFWi2rP  --peer /ip4/172.99.1.6/tcp/13000/p2p/16Uiu2HAmNhdZermeUdkQuZeathnkEiWHH8KFJcSsXPeTR3JA6Zue 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=21d4f1dcef2492ae517685309a9359193b12fd4ab84194417b6d9ef0c6f66922

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13003:4000"
      - "14003:3500"
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/beacon-4:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.5

  beacon-5:
    image: tscel/beacon-v5.0.1-t1-reorg:0805
    container_name: beacon-5
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.2/tcp/13000/p2p/16Uiu2HAmDashuTodN3KUjWFM3yvcUE5h1qUHYGnEGJ98vFaFVB9W  --peer /ip4/172.99.1.3/tcp/13000/p2p/16Uiu2HAmViS3SUn4cBmMGkRx6CBzgSFHu7JJY6oztwvbhzPKrQSQ  --peer /ip4/172.99.1.4/tcp/13000/p2p/16Uiu2HAkuVr12eYtMNuxcRcTYj9PYHxVTz8TYkDjGgg8ZtFWi2rP  --peer /ip4/172.99.1.5/tcp/13000/p2p/16Uiu2HAm42EM98s9Feq2VoWP6R78FtHs6T9sWY3HaGFn7assWc87 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=fc93695551533f08ee0350ac8c17501d1c3c5adbc7ebb00211934ec923a57ad7

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13004:4000"
      - "14004:3500"
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/beacon-5:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.6

  validator-1:
    image: tscel/validator-v5.0.1-t1-reorg:0805
    container_name: validator-1
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=85
      - VALIDATORS_INDEX=0
      - BEACONRPC=beacon-1:4000
      - ATTACKER_SERVICE_URL=http://172.17.0.1:12000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/validator-1:/root/validatordata
    depends_on:
      - beacon-1
    networks:
      - meta

  validator-2:
    image: tscel/validator-v5.0.1-t1-reorg:0805
    container_name: validator-2
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=85
      - BEACONRPC=beacon-2:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/validator-2:/root/validatordata
    depends_on:
      - beacon-2
    networks:
      - meta

  validator-3:
    image: tscel/validator-v5.0.1-t1-reorg:0805
    container_name: validator-3
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=136
      - BEACONRPC=beacon-3:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/validator-3:/root/validatordata
    depends_on:
      - beacon-3
    networks:
      - meta

  validator-4:
    image: tscel/validator-v5.0.1-t1-reorg:0805
    container_name: validator-4
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=187
      - BEACONRPC=beacon-4:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/validator-4:/root/validatordata
    depends_on:
      - beacon-4
    networks:
      - meta

  validator-5:
    image: tscel/validator-v5.0.1-t1-reorg:0805
    container_name: validator-5
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=18
      - VALIDATORS_INDEX=238
      - BEACONRPC=beacon-5:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ${BASEDIR}./config:/root/config
      - ${BASEDIR}./data/validator-5:/root/validatordata
    depends_on:
      - beacon-5
    networks:
      - meta


networks:
  meta:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16
